//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebserviceClient.srv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:mynamespace", ConfigurationName="srv.mynamePortType")]
    public interface mynamePortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (xsd:mynamespace) of message get_messageRequest does not match the default value (urn:mynamespace)
        [System.ServiceModel.OperationContractAttribute(Action="http://new.kgnic.ru/wp-content/plugins/orderform/webservice.php/get_message", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(orderItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(order))]
        WebserviceClient.srv.get_messageResponse get_message(WebserviceClient.srv.get_messageRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:mynamespace")]
    public partial class order : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string organizationfullField;
        
        private string organizationshortField;
        
        private string fIOdirField;
        
        private string positiondirField;
        
        private string reasondirField;
        
        private string phonedirField;
        
        private string fIOcontField;
        
        private string positioncontField;
        
        private string phonecontField;
        
        private string emailField;
        
        private string iNNField;
        
        private string kPPField;
        
        private string oGRNField;
        
        private string schetField;
        
        private string korrschetField;
        
        private string bIKField;
        
        private string banknameField;
        
        private string addrlegalField;
        
        private string addrfactField;
        
        private string commentField;
        
        private orderItem[] itemsField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public string Organizationfull {
            get {
                return this.organizationfullField;
            }
            set {
                this.organizationfullField = value;
                this.RaisePropertyChanged("Organizationfull");
            }
        }
        
        /// <remarks/>
        public string Organizationshort {
            get {
                return this.organizationshortField;
            }
            set {
                this.organizationshortField = value;
                this.RaisePropertyChanged("Organizationshort");
            }
        }
        
        /// <remarks/>
        public string FIOdir {
            get {
                return this.fIOdirField;
            }
            set {
                this.fIOdirField = value;
                this.RaisePropertyChanged("FIOdir");
            }
        }
        
        /// <remarks/>
        public string Positiondir {
            get {
                return this.positiondirField;
            }
            set {
                this.positiondirField = value;
                this.RaisePropertyChanged("Positiondir");
            }
        }
        
        /// <remarks/>
        public string Reasondir {
            get {
                return this.reasondirField;
            }
            set {
                this.reasondirField = value;
                this.RaisePropertyChanged("Reasondir");
            }
        }
        
        /// <remarks/>
        public string Phonedir {
            get {
                return this.phonedirField;
            }
            set {
                this.phonedirField = value;
                this.RaisePropertyChanged("Phonedir");
            }
        }
        
        /// <remarks/>
        public string FIOcont {
            get {
                return this.fIOcontField;
            }
            set {
                this.fIOcontField = value;
                this.RaisePropertyChanged("FIOcont");
            }
        }
        
        /// <remarks/>
        public string Positioncont {
            get {
                return this.positioncontField;
            }
            set {
                this.positioncontField = value;
                this.RaisePropertyChanged("Positioncont");
            }
        }
        
        /// <remarks/>
        public string Phonecont {
            get {
                return this.phonecontField;
            }
            set {
                this.phonecontField = value;
                this.RaisePropertyChanged("Phonecont");
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
                this.RaisePropertyChanged("INN");
            }
        }
        
        /// <remarks/>
        public string KPP {
            get {
                return this.kPPField;
            }
            set {
                this.kPPField = value;
                this.RaisePropertyChanged("KPP");
            }
        }
        
        /// <remarks/>
        public string OGRN {
            get {
                return this.oGRNField;
            }
            set {
                this.oGRNField = value;
                this.RaisePropertyChanged("OGRN");
            }
        }
        
        /// <remarks/>
        public string Schet {
            get {
                return this.schetField;
            }
            set {
                this.schetField = value;
                this.RaisePropertyChanged("Schet");
            }
        }
        
        /// <remarks/>
        public string Korrschet {
            get {
                return this.korrschetField;
            }
            set {
                this.korrschetField = value;
                this.RaisePropertyChanged("Korrschet");
            }
        }
        
        /// <remarks/>
        public string BIK {
            get {
                return this.bIKField;
            }
            set {
                this.bIKField = value;
                this.RaisePropertyChanged("BIK");
            }
        }
        
        /// <remarks/>
        public string Bankname {
            get {
                return this.banknameField;
            }
            set {
                this.banknameField = value;
                this.RaisePropertyChanged("Bankname");
            }
        }
        
        /// <remarks/>
        public string Addrlegal {
            get {
                return this.addrlegalField;
            }
            set {
                this.addrlegalField = value;
                this.RaisePropertyChanged("Addrlegal");
            }
        }
        
        /// <remarks/>
        public string Addrfact {
            get {
                return this.addrfactField;
            }
            set {
                this.addrfactField = value;
                this.RaisePropertyChanged("Addrfact");
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        public orderItem[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:mynamespace")]
    public partial class orderItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productField;
        
        private int quantityField;
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
                this.RaisePropertyChanged("Product");
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_message", WrapperNamespace="xsd:mynamespace", IsWrapped=true)]
    public partial class get_messageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string number;
        
        public get_messageRequest() {
        }
        
        public get_messageRequest(string number) {
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_messageResponse", WrapperNamespace="xsd:mynamespace", IsWrapped=true)]
    public partial class get_messageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public WebserviceClient.srv.order[] output;
        
        public get_messageResponse() {
        }
        
        public get_messageResponse(WebserviceClient.srv.order[] output) {
            this.output = output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mynamePortTypeChannel : WebserviceClient.srv.mynamePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mynamePortTypeClient : System.ServiceModel.ClientBase<WebserviceClient.srv.mynamePortType>, WebserviceClient.srv.mynamePortType {
        
        public mynamePortTypeClient() {
        }
        
        public mynamePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mynamePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mynamePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mynamePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebserviceClient.srv.get_messageResponse WebserviceClient.srv.mynamePortType.get_message(WebserviceClient.srv.get_messageRequest request) {
            return base.Channel.get_message(request);
        }
        
        public WebserviceClient.srv.order[] get_message(string number) {
            WebserviceClient.srv.get_messageRequest inValue = new WebserviceClient.srv.get_messageRequest();
            inValue.number = number;
            WebserviceClient.srv.get_messageResponse retVal = ((WebserviceClient.srv.mynamePortType)(this)).get_message(inValue);
            return retVal.output;
        }
    }
}
